# Express any dependencies
PROTOBUF=     # full / lite / none
WASM_DEPS=    # absl_base re2 ...

# Include the SDK Makefile
@echo "GitHub Workspace Directory: $(GITHUB_WORKSPACE)"

PROXY_WASM_CPP_SDK=/home/runner/work/test-1/test-1/proxy-wasm-cpp-sdk
include ${PROXY_WASM_CPP_SDK}/Makefile
