name: Add header service

on: # The events that trigger the workflow
  push:
    branches:
      - test #Trigger on push to the 'main' branch
    paths:
      - "**/*"
  pull_request:
    branches:
      - main # Trigger when a pull request is made to 'main'

jobs:
  build: # Define jobs that will run in this workflow
    runs-on: ubuntu-latest # The operating system to run the job
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2
      # Print the current directory for debugging
      # - name: Print current directory
      #   run: pwd
      # - name: list current directory
      #   run: ls $(pwd)
      - name: Run a Command
        run: |
          git clone https://github.com/proxy-wasm/proxy-wasm-cpp-sdk.git
          cd proxy-wasm-cpp-sdk
          pwd
          ls -l 
          docker build -t wasmsdk:v3 -f Dockerfile-sdk .
