name: Add header service

on: # The events that trigger the workflow
  push:
    branches:
      - test #Trigger on push to the 'main' branch
    paths:
      - "**/*"
  pull_request:
    branches:
      - main # Trigger when a pull request is made to 'main'

jobs:
  build: # Define jobs that will run in this workflow
    runs-on: ubuntu-latest # The operating system to run the job
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2
      # Print the current directory to check where we are
      - name: Print current directory
        run: |
          pwd
          ls
      - name: Clone proxy-wasm-cpp-sdk
        run: |
          
          cd proxy-wasm-cpp-sdk && docker build -t wasmsdk:v3 -f Dockerfile-sdk proxy-wasm-cpp-sdk/
      # - name: Makfile print
      #      run: make print-pwd
      - name: Change Dir to addheader
        run: |
          cd addheader
          docker run -v $(pwd):/work -w /work wasmsdk:v3 /build_wasm.sh addheader.wasm
          docker commit `docker ps -l | grep wasmsdk:v3 | awk '{print $1}'` wasmsdk:v3
      - name: Copy wasm file to package dir 
        run: |
          cp -f addheader.wasm package/plugin.wasm

